#!/bin/bash
#Script Author: Eric Goodwin
#Assignment 1 for CS 2750 Spring Semester 2016



if [ "$#" = 0 ]  #takes users input for script
  then
    number=20 #default if no input
  else
    number=$1  #stores users input
fi

for (( i=1; i<=$number; i++ )) #prints ascending from 1 to value entered.  if divisble by 3, prints Fizz instead.  if divisble by 5, prints Buzz, if divisble by both it prings FizzBuzz
do

	if (( $i % 5 == 0  && $i % 3 == 0 ))  #tests i if divisible by 3 and 5 and prints FizzBuzz if true
	  then 
	     echo "FizzBuzz"
	elif (( $i % 5 == 0 ))  #tests i if divisible by 5 only and prints Buzz if true
	  then 
	     echo "Buzz"
	elif (( $i % 3 == 0 ))  #tests i if divisible by 3 only and prints Fizz if true
	  then
	    echo "Fizz"
	else
	    echo $i
	fi
done

exit 0
